#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG)
verify_app_name "$APP"

PLUGIN_BASE_PATH="${PLUGIN_PATH}"
if [[ -n ${DOKKU_API_VERSION} ]]; then
  PLUGIN_BASE_PATH="${PLUGIN_ENABLED_PATH}"
fi

source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_BASE_PATH/domains/functions"

DOMAINS=""

get_app_domains | while read domain
do
  DOMAINS="${domain} ${DOMAINS}"
done

if [ 0 -lt ${#DOMAINS} ]; then
    dokku_log_info1 "Application domains: ${DOMAINS}"
    dokku docker-options:add "$APP" run,deploy "-e APP_DOMAINS=${DOMAINS}"
fi

