#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG)
verify_app_name "$APP"

PLUGIN_BASE_PATH="${PLUGIN_PATH}"
if [[ -n ${DOKKU_API_VERSION} ]]; then
  PLUGIN_BASE_PATH="${PLUGIN_ENABLED_PATH}"
fi
source "${PLUGIN_BASE_PATH}/common/functions"

if [[ -f "${DOKKU_ROOT}/VHOST" ]]; then
    VHOST=$(< "${DOKKU_ROOT}/VHOST")
else
    VHOST=$(< "${DOKKU_ROOT}/HOSTNAME")
fi

SUBDOMAIN=${APP/%\.${VHOST}/}
hostname=$(: | plugn trigger nginx-hostname $APP $SUBDOMAIN $VHOST)

if [[ ! -n ${hostname} ]]; then
  if [[ "${APP}" == *.* ]] && [[ "${SUBDOMAIN}" == "${APP}" ]]; then
    hostname="${APP/\//-}"
  else
    hostname="${APP/\//-}.${VHOST}"
  fi
fi

dokku_log_info1 "Application domain: ${hostname}"
dokku docker-options:add "$APP" run,deploy "-e APP_DOMAIN=${hostname}"


